export const tracks = [
	{
		id: "1",
		cover: "/assets/thumb/bg-1.png",
		thumbnail: "/assets/thumb/bg-1.png",
		title: "Great Escape",
		type: "youtube",
		UpVotes: 5,
	},
	{
		id: "2",
		cover: "/assets/thumb/bg-2.png",
		thumbnail: "/assets/thumb/bg-2.png",
		title: "Midnight Symphony",
		type: "spotify",
		UpVotes: 8,
	},
	{
		id: "3",
		cover: "/assets/thumb/bg-3.png",
		thumbnail: "/assets/thumb/bg-3.png",
		title: "Ocean Waves",
		type: "youtube",
		UpVotes: 3,
	},
	{
		id: "4",
		cover: "/assets/thumb/bg-4.png",
		thumbnail: "/assets/thumb/bg-4.png",
		title: "Desert Dreams",
		type: "soundcloud",
		UpVotes: 6,
	},
	{
		id: "5",
		cover: "/assets/thumb/bg-5.png",
		thumbnail: "/assets/thumb/bg-5.png",
		title: "Urban Beats",
		type: "spotify",
		UpVotes: 10,
	},
	{
		id: "6",
		cover: "/assets/thumb/bg-6.png",
		thumbnail: "/assets/thumb/bg-6.png",
		title: "Mountain Echo",
		type: "youtube",
		UpVotes: 7,
	},
	{
		id: "7",
		cover: "/assets/thumb/bg-7.png",
		thumbnail: "/assets/thumb/bg-7.png",
		title: "Neon Lights",
		type: "spotify",
		UpVotes: 9,
	},
	{
		id: "8",
		cover: "/assets/thumb/bg-8.png",
		thumbnail: "/assets/thumb/bg-8.png",
		title: "Summer Vibes",
		type: "soundcloud",
		UpVotes: 4,
	},
	{
		id: "9",
		cover: "/assets/thumb/bg-9.png",
		thumbnail: "/assets/thumb/bg-9.png",
		title: "Cosmic Journey",
		type: "youtube",
		UpVotes: 12,
	},
	{
		id: "10",
		cover: "/assets/thumb/bg-10.png",
		thumbnail: "/assets/thumb/bg-10.png",
		title: "Electric Dreams",
		type: "spotify",
		UpVotes: 8,
	},
];